name: ss-maxben-dev
channels:
- conda-forge
dependencies:
- python>3.11, <3.14
- numpy
- numba>=0.54
- scipy>=1.7.1
- pandas>=1.2.5
- matplotlib
- plotly
- python-kaleido
- bokeh
- dask>=2.30.0
- dask-core>=2.30.0
- distributed>=2.30.1
- paramtools>=0.20.0
- black
- requests
- xlwt
- statsmodels
- linearmodels
- jupyter
- ipykernel
- ipython
- pip
- pip:
  - openpyxl>=3.1.2
  - pandas-datareader
  - ogcore==0.14.10
  - taxcalc==5.2.0
  - ogusa==0.3.1
